docs(ja): translate directory-structure/middleware
nuxt/nuxtjs.org pull request #1023
Opened 2020-11-24 14:24 UTC by Katakuranatsumi

please review this PR.
resolve vuejs-jp#145

2020-11-28 15:19 UTC, inouetakuya requested changes
自然な日本語で読みやすかったです。書式についていくつかコメントをさせてもらいました ☺️

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +  - question: ミドルウェアが呼び出されるときにSSRがfalseに設定されている場合は？
```suggestion
  - question: ミドルウェアが呼び出されるときに SSR が false に設定されている場合は？
```

英数字の両端に半角スペースを入れます 📝 

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E5%8D%8A%E8%A7%92%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E3%81%A7%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%99%E3%83%83%E3%83%88%E4%B8%A1%E7%AB%AF%E3%82%92%E5%85%A5%E3%82%8C%E3%81%A6%E8%AA%AD%E3%81%BF%E3%82%84%E3%81%99%E3%81%8F

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +共有ミドルウェアは、 `middleware/` ディレクトリに配置する必要があります。ファイル名はミドルウェアの名前になります（ `middleware/auth.js` は  `auth` ミドルウェアになります）。関数を直接使用して、ページ固有のミドルウェアを定義することもできます。
```suggestion
共有ミドルウェアは、`middleware/` ディレクトリに配置する必要があります。ファイル名はミドルウェアの名前になります（`middleware/auth.js` は `auth` ミドルウェアになります）。関数を直接使用して、ページ固有のミドルウェアを定義することもできます。
```

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E5%8D%8A%E8%A7%92%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E3%81%A7%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%99%E3%83%83%E3%83%88%E4%B8%A1%E7%AB%AF%E3%82%92%E5%85%A5%E3%82%8C%E3%81%A6%E8%AA%AD%E3%81%BF%E3%82%84%E3%81%99%E3%81%8F

> 例外として、句読点の前後にアルファベットがある場合は、スペースを入れなくてもいいです。

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +次に、 `nuxt.config.js` で、`router.middleware` キーを使用します。
```suggestion
次に、`nuxt.config.js` で、`router.middleware` キーを使用します。
```

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +ミドルウェア(複数でも) を特定のレイアウト、またはページに追加することもできます。
```suggestion
ミドルウェア（複数でも）を特定のレイアウト、またはページに追加することもできます。
```

カッコは全角を使います 📝

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +  // ユーザが認証されていない場合
```suggestion
  // ユーザーが認証されていない場合
```

他の箇所を検索してみたところ、大半が `ユーザー` だったので合わせましょうか。他のページで `ユーザ` となっている箇所は別途修正しておきます。

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +      // ユーザが認証されていない場合
```suggestion
      // ユーザーが認証されていない場合
```

2020-11-28 15:19 UTC, inouetakuya commented on content/ja/guides/directory-structure/middleware.md
> +特定のページにのみミドルウェアを使用する必要がある場合は、そのミドルウェアの関数 (または関数の配列)を直接使用できます:
```suggestion
特定のページにのみミドルウェアを使用する必要がある場合は、そのミドルウェアの関数（または関数の配列）を直接使用できます:
```

2020-11-29 09:56 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +  - question: ミドルウェアが呼び出されるときにSSRがfalseに設定されている場合は？
レビューありがとうございます🙇‍♀️
こちら f47ae4b で修正しましたmm

2020-11-29 09:56 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +共有ミドルウェアは、 `middleware/` ディレクトリに配置する必要があります。ファイル名はミドルウェアの名前になります（ `middleware/auth.js` は  `auth` ミドルウェアになります）。関数を直接使用して、ページ固有のミドルウェアを定義することもできます。
こちら 7474b47 で修正しましたmm

2020-11-29 09:57 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +次に、 `nuxt.config.js` で、`router.middleware` キーを使用します。
こちらも 7474b47 で修正しましたmm

2020-11-29 09:58 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +ミドルウェア(複数でも) を特定のレイアウト、またはページに追加することもできます。
こちら 11f3f55 で修正しましたmm

2020-11-29 09:58 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +特定のページにのみミドルウェアを使用する必要がある場合は、そのミドルウェアの関数 (または関数の配列)を直接使用できます:
こちらも 11f3f55 で修正しましたmm

2020-11-29 09:58 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +  // ユーザが認証されていない場合
こちら 7fec5fe で修正しましたmm

2020-11-29 09:59 UTC, Katakuranatsumi commented on content/ja/guides/directory-structure/middleware.md
> +      // ユーザが認証されていない場合
こちらも 7fec5fe で修正しましたmm

2020-11-29 11:35 UTC, inouetakuya reviewed
修正ありがとうございます！

- [docs(ja): add missing pages in English to content/ja/guides/ by inouetakuya · Pull Request #1041 · nuxt/nuxtjs.org](https://github.com/nuxt/nuxtjs.org/pull/1041#event-4048793863)

で一旦英語のままのファイルを設置しているので、このプルリクエストの日本語のファイルと差し替え（= コンフリクト解消）をお願いします！

2020-11-29 12:03 UTC, Katakuranatsumi commented
@inouetakuya 
再度のご確認ありがとうございましたmm
日本語のファイルと差し替え（= コンフリクト解消）を行いましたので、よろしくお願い致します🙏

2020-11-29 12:27 UTC, inouetakuya approved these changes
Thank you for your contribution :+1:

2020-11-29 12:41 UTC, merged