docs(ja): translate configuration-servermiddleware
nuxt/nuxtjs.org pull request #1044
Opened 2020-11-29 10:00 UTC by aytdm

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/136
ref: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/_archives/api/configuration-servermiddleware.md

2020-11-29 12:14 UTC, inouetakuya requested changes
🙏

2020-11-29 12:14 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-servermiddleware.md
> +  // req は Node.js の HTTPリクエストオブジェクトです
```suggestion
  // req は Node.js の HTTP リクエストオブジェクトです
```

2020-11-29 12:14 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-servermiddleware.md
> +  // res は Node.js の HTTPレスポンスオブジェクトです
```suggestion
  // res は Node.js の HTTP レスポンスオブジェクトです
```

2020-12-02 13:15 UTC, aytdm commented on content/ja/guides/configuration-glossary/configuration-servermiddleware.md
> +  // req は Node.js の HTTPリクエストオブジェクトです
🙈 
ありがとうございます、修正しました

2020-12-09 04:05 UTC, inouetakuya approved these changes
Thank you!

2020-12-09 04:05 UTC, merged