docs(ja): translate directory-structure-assets
nuxt/nuxtjs.org pull request #1127
Opened 2021-01-05 16:19 UTC by Shohei-Japan

Please review this PR.

resolve vuejs-jp#115

2021-01-05 16:20 UTC, Shohei-Japan commented on content/ja/guides/directory-structure/assets.md
> +ルートディレクトリには、エイリアスの `~~` や `@@` を使用することができます。
この下にあるスペイン語キーボードでのタイプ方法については、日本人ユーザ向けでないと思い省きました。

2021-01-05 16:21 UTC, Shohei-Japan commented
nuxt 2.8 の記述で近しい表現があれば、自然な言葉遣いで引用しています。
https://develop365.gitlab.io/nuxtjs-2.8.X-doc/ja/guide/assets/

2021-01-06 01:25 UTC, inouetakuya approved these changes
LGTM!!

Thank you for your contribution :+1:

2021-01-06 09:36 UTC, inouetakuya requested changes
Could you fix conflicts?

2021-01-06 13:40 UTC, Shohei-Japan commented
@inouetakuya 
レビューいただきありがとうございます。コンフリクトを解消いたしました。

`check-pr-links (nuxt)` のエラーが出てしまっています。本 PR 内での対応で関係するところはないように思っているのですが、対応方法があれば伺いたいです 🙏

2021-01-07 05:05 UTC, inouetakuya approved these changes
> check-pr-links (nuxt) のエラーが出てしまっています。本 PR 内での対応で関係するところはないように思っているのですが、対応方法があれば伺いたいです 🙏

他のブランチでの実行（例えば master ブランチでの実行）と被ると失敗する可能性が高そうです。

私の場合は他の言語のやつがこけていても無視していますが、nuxt と nuxt-ja がこけていたら念のため Rerun しています。

今回も Rerun しました。-> nuxt も成功しました 🎉 

https://github.com/nuxt/nuxtjs.org/pull/1127/checks?check_run_id=1660560221

というわけで LGTM です！おつかれさまでした！！

2021-01-07 05:05 UTC, merged