Maxnvk/russian translation
nuxt/nuxtjs.org pull request #1128
Opened 2021-01-06 09:41 UTC by MaxNvk

2021-01-06 12:21 UTC, DreaMinder requested changes
Nice job! Almost there, but looks like you need to merge master into your branch and go through English version again, there were some changes lately. The most important changes - /guides dir moved to /2.x. Please update accordingly.

Also, in case you are wondering who am I. I'm a reviewer of Russian translation team. In case you want to join our workflow or just avoid translating the same pages we are working on, ping me on t.me/dreaminder and I'll add you to a Telegram chat. We are about to release Consepts section.

2021-01-06 12:21 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-fetch.md
> +Вы можете использовать его каждый раз когда вам необходимо получить **асинхронные** данные. `fetch` вызывается на стороне сервера когда происходит рендеринг рута, и на строне клиента при переходе меж
```suggestion
Вы можете использовать его каждый раз когда вам необходимо получить **асинхронные** данные. `fetch` вызывается на стороне сервера когда происходит рендеринг представления, и на стороне клиента при переходе между страницами.
```

мы используем термин "представление" на других страницах доки. Или можно использовать слово "путь", но не рут.

2021-01-06 12:21 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-fetch.md
> +### Когда использовать fetch?
Этого абзаца нет в обновленной англ. доке, не то чтоб он сильно мешал, но наверное лучше делать структуру страницы похожей чтобы потом легче было вносить правки.

2021-01-06 12:21 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-key.md
> +Есть несколько путей для задания key. Для большей информации, обратитесь к свойсту `nuxtChildKey` в [nuxt component](/guides/features/nuxt-components)
```suggestion
Есть несколько путей для задания key. Для подробной информации, обратитесь к свойсту `nuxtChildKey` в [nuxt component](/guides/features/nuxt-components)
```

2021-01-07 11:37 UTC, MaxNvk commented on content/ru/guides/components-glossary/pages-fetch.md
> +Вы можете использовать его каждый раз когда вам необходимо получить **асинхронные** данные. `fetch` вызывается на стороне сервера когда происходит рендеринг рута, и на строне клиента при переходе меж
Поправил, полностью заново перевел эту страницу так как её контент сильно поменялся. Также проверил остальные страницы которые делал, они остались без изменений в оригинале

2021-01-08 13:51 UTC, DreaMinder requested changes
Just a couple of minor suggestions

2021-01-08 13:51 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-fetch.md
> +    // В качестве альтернативы, для большего контроля функця может быть передаваться с доступом к состоянию компонента
```suggestion
    // В качестве альтернативы, для большего контроля, может быть передаваться функция с доступом к состоянию компонента
```

2021-01-08 13:51 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-fetch.md
> +      // как часть создания уникального fetchKey.
```suggestion
      // как часть генерации уникального fetchKey.
```
"создания" режет ухо, если есть другие предложения - я не против

2021-01-08 13:51 UTC, DreaMinder commented on content/ru/guides/components-glossary/pages-key.md
> +Есть несколько путей для задания key. Для подробной информации, обратитесь к свойсту `nuxtChildKey` в [nuxt component](/docs/2.x/features/nuxt-components)
```suggestion
Есть несколько способов задать key. Для подробной информации, обратитесь к свойсту `nuxtChildKey` в [nuxt component](/docs/2.x/features/nuxt-components)
```

2021-01-08 18:34 UTC, MaxNvk commented
> Just a couple of minor suggestions
> 
> But still, looks like Github won't let you merge... Maybe take a look here https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch?

I up to date my branch, it must be okay.

2021-01-08 19:16 UTC, DreaMinder approved these changes
Looks good to me 👍

2021-01-13 11:51 UTC, debs-obrien commented
great work guys

2021-01-13 11:52 UTC, merged