docs(i18n-id): translate modules.md and several config section into Indonesia
nuxt/nuxtjs.org pull request #1169
Opened 2021-01-19 00:48 UTC by R1dwanMaulana

## Overview
this is part of #549 

## Changes

translate the following files
<modules.md>

2021-01-22 14:43 UTC, febrihidayan reviewed
Masih banyak, mas yang perlu diperbaiki 👏

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +title: modules
Huruf pertama kapital

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +description: Nuxt.js menyediakan sistem modul tingkat tinggi yang memungkinkan untuk memperluas inti. Modul adalah fungsi yang dipanggil secara berurutan saat mem-boot Nuxt.js.
men-boot menjadi men-_boot_ (`men-_boot_`)

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +Modul adalah ekstensi Nuxt.js yang dapat memperluas fungsionalitas inti kerangka kerja dan menambahkan integrasi tanpa akhir. Setelah Anda menginstal modul, Anda dapat menambahkannya ke file nuxt.con
file menjadi berkas

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +    // Using package name
komen pada skrip kalau bisa diartikan juga mas

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +`moduleOptions`: Ini adalah objek yang diteruskan menggunakan _larik_ `modules` oleh pengguna. Kita dapat menggunakannya untuk menyesuaikan perilakunya.
larik bahasa indonesia, mas

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +`this.options`: Anda bisa langsung mengakses opsi Nuxt.js menggunakan referensi ini. Ini adalah konten dari pengguna `nuxt.config.js` dengan semua opsi default yang ditetapkan padanya. Ini dapat digu
default bisa diartikan bawaan

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +- **Error**: Error yang tidak tertangani saat memanggil hook.
Error diartikan galat

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +- **Listen**: Server internal Nuxt mulai mendengarkan. (Menggunakan nuxt start atau nuxt dev)
Server menjadi peladen

2021-01-22 14:43 UTC, febrihidayan commented on content/id/guides/directory-structure/modules.md
> +Tidak semua modul akan melakukan semuanya secara sinkron. Misalnya, Anda mungkin ingin mengembangkan modul yang perlu mengambil beberapa API atau melakukan Operasi asinkron. Untuk ini, Nuxt.js menduk
dibuat miring bahasa inggrisnya

2021-01-23 01:37 UTC, R1dwanMaulana commented on content/id/guides/directory-structure/modules.md
> +title: modules
klo dilihat di source nya sih title sama modules itu pakek huruf kecil semua mas

2021-02-26 17:12 UTC, jefrydco requested changes

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Template dan plugin terdaftar dapat memanfaatkan [template lodash](https://lodash.com/docs/4.17.4#template) untuk mengubah keluaran plugin terdaftar secara bersyarat.
```suggestion
Templat dan plugin terdaftar dapat memanfaatkan [templat lodash](https://lodash.com/docs/4.17.4#template) untuk mengubah hasil keluaran plugin yang terdaftar dengan syarat-syarat tertentu.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +// Set Google Analytics UA
```suggestion
// Mengatur Google Analytics UA
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +// Dev only code
```suggestion
// Kode yang dijalankan ketika proses pengembangan
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +  // Register `plugin.js` template
```suggestion
  // Mendaftarkan templat `plugin.js`
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +      // Nuxt will replace `options.ua` with `123` when copying plugin to project
```suggestion
      // Nuxt akan mengganti `options.ua` dengan `123` ketika menggandakan plugin untuk proyek yang kita buat
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +      // conditional parts with dev will be stripped from plugin code on production builds
```suggestion
      // bagian kode yang menggunakan mode pengembangan akan dihilangkan dari kode plugin pada hasil produksi
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +      // Customize existing loaders
```suggestion
      // Meng-_custom_ _loader_ yang sebelumnya tersedia
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +      // Refer to source code for Nuxt internals:
```suggestion
      // Mengacu pada kode sumber internal Nuxt berikut:
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Tidak semua modul akan melakukan semuanya secara sinkron. Misalnya, Anda mungkin ingin mengembangkan modul yang perlu mengambil beberapa API atau melakukan Operasi asinkron. Untuk ini, Nuxt.js menduk
```suggestion
Tidak semua modul akan melakukan semuanya secara sinkronus. Misalnya, Anda mungkin ingin mengembangkan modul yang perlu mengambil beberapa API atau melakukan operasi asinkronus. Dalam kasus ini, Nuxt.js mendukung modul asinkronus yang dapat mengembalikan Promise atau memanggil callback.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +  // You can do async work here using `async`/`await`
```suggestion
  // Anda dapat melakukan pekerjaan asinkronus menggunakan `async`/`await`
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +      // Do something by extending Nuxt routes
```suggestion
      // Melakukan sesuatu dengan meng-_extend_ _route_ Nuxt
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Ada lebih banyak kait dan kemungkinan untuk modul. Silakan baca [Nuxt Internals](/docs/2.x/internals-glossary/internals) untuk mengetahui lebih lanjut tentang API nuxt-internal.
```suggestion
Ada lebih banyak kait (_hook_) dan kemungkinan yang dapat kita lakukan untuk modul. Silakan baca [Internal Nuxt](/docs/2.x/internals-glossary/internals) untuk mengetahui lebih lanjut tentang API nuxt-internal.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +`module.exports.meta`: Baris ini diperlukan jika Anda menerbitkan modul sebagai paket npm. Nuxt secara internal menggunakan meta untuk bekerja lebih baik dengan paket Anda.
```suggestion
`module.exports.meta`: Baris ini diperlukan jika Anda menerbitkan modul sebagai paket NPM. Nuxt secara internal menggunakan meta untuk bekerja lebih baik dengan paket Anda.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Beberapa modul hanya diimpor selama pengembangan dan waktu pembuatan. Penggunaan `buildModules` membantu mempercepat proses produksi dan juga secara signifikan mengurangi ukuran `node_modules` Anda u
```suggestion
Beberapa modul hanya diimpor selama pengembangan dan waktu pembuatan. Penggunaan `buildModules` membantu mempercepat proses produksi dan juga secara signifikan mengurangi ukuran `node_modules` Anda untuk penerapan produksi. Silakan merujuk ke dokumentasi berikut untuk setiap modul guna mengetahui apakah direkomendasikan untuk menggunakan `modules` atau `buildModules`.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Jika Anda adalah pembuat modul, Sangat disarankan untuk menyarankan pengguna menginstal paket Anda sebagai `devDependency` dan gunakan `buildModules` alih-alih `modules` untuk `nuxt.config.js`.
```suggestion
Jika Anda adalah pembuat modul, sangat disarankan untuk menyarankan pengguna memasang paket Anda sebagai `devDependency` dan gunakan `buildModules` alih-alih `modules` untuk `nuxt.config.js`.
```

2021-02-26 17:12 UTC, jefrydco commented on content/id/guides/directory-structure/modules.md
> +Jika Anda akan menawarkan menggunakan `buildModules`, harap sebutkan bahwa fitur ini hanya tersedia sejak Nuxt v2.9. Pengguna yang lebih tua harus mengupgrade Nuxt atau menggunakan bagian `modules`.
```suggestion
Jika Anda akan menyarankan untuk pengguna Anda menggunakan `buildModules`, harap sebutkan bahwa fitur ini hanya tersedia sejak Nuxt v2.9. Pengguna Nuxt versi sebelumnya harus memutakhirkan Nuxt atau menggunakan bagian `modules`.
```

2021-02-26 17:14 UTC, jefrydco commented
Btw Mas @febrihidayan boleh minta tolong tambahkan tag `Indonesian` untuk memudahkan kita filter pull request

2021-02-26 17:43 UTC, febrihidayan commented
@jefrydco  bukannya tag `Indonesian` sudah ada mas dengan nama `indonesia`

2021-02-26 18:30 UTC, jefrydco commented
Oiya baru ngeh, thank you then.

2021-02-28 11:05 UTC, febrihidayan approved these changes

2021-02-28 11:32 UTC, febrihidayan approved these changes

2021-02-28 11:32 UTC, merged