docs(id): translate directory structure to indonesian
nuxt/nuxtjs.org pull request #1276
Opened 2021-02-18 16:12 UTC by fajarafriansh

### Overview
this is part of #549

### Changes
📝 guides -> directory structure
- [x] nuxt-config.md
- [ ] modules.md

2021-02-18 16:14 UTC, fajarafriansh commented
tolong di review `nuxt-config.md` dulu mas @febrihidayan, file `modules.md` akan saya commit besok atau lusa.

2021-02-18 16:31 UTC, febrihidayan reviewed
Saya baru ingat mas, kalau bisa kata Kamu/Kau diganti dengan Anda. Sedangkan kata root bisa dibuat miring atau diartikan dengan akar http://kateglo.com/?phrase=root&mod=glossary

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Opsi ini memungkinkan kamu mengonfigurasi berbagai pengaturan untuk langkah `build`, termasuk ` loaders`, `filenames`, konfigurasi `webpack` dan `transpilation`.
... , konfigurasi `webpack`, dan `transpilation`.

Ada koma sebelum kata DAN, mas. karena lebih dari 2 penyebut

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Dengan menghilangkan ekstensi, misalnya jika kamu memiliki file css dan memutuskan untuk menggunakan sass, kamu tidak perlu memperbarui nuxt.config karena akan menggunakan ekstensi baru selama nama f
file menjadi berkas

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Kamu dapat menyesuaikan jalur dengan menggunakan `--dotenv <file>` atau menonaktifkan sepenuhnya dengan `--dotenv false`. Misalnya, kamu mungkin menetapkan file `.env` yang berbeda dalam lingkungan p
file menjadi berkas

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Konfigurasi pribadi kamu dapat diekspos jika kamu menggunakan `$config` di luar konteks khusus server (misalnya, jika kamu menggunakan `$config` di `fetch`, `asyncData` atau langsung di dalam templat
server menjadi peladen

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
belum diterjemahkan

2021-02-18 16:31 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Opsi ini memungkinkan kamu untuk mendefinisikan _plugin_ JavaScript yang harus dijalankan sebelum _instantiate_ root aplikasi Vue.js.
root di miringkan

2021-02-18 16:35 UTC, fajarafriansh commented on content/id/guides/directory-structure/nuxt-config.md
> +Konfigurasi pribadi kamu dapat diekspos jika kamu menggunakan `$config` di luar konteks khusus server (misalnya, jika kamu menggunakan `$config` di `fetch`, `asyncData` atau langsung di dalam templat
atau tetap server-only, tapi dimiringkan mas?

2021-02-18 16:38 UTC, fajarafriansh commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
wkwkwk, ternyata ada yang terlewat

2021-02-18 16:41 UTC, fajarafriansh commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
bagian 'Yarn workspace-styled mono-repository' diterjemahkan mas? atau miring saja?

2021-02-18 16:49 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
> bagian 'Yarn workspace-styled mono-repository' diterjemahkan mas? atau miring saja?

Coba saya lihat dulu, mas

2021-02-18 16:50 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Konfigurasi pribadi kamu dapat diekspos jika kamu menggunakan `$config` di luar konteks khusus server (misalnya, jika kamu menggunakan `$config` di `fetch`, `asyncData` atau langsung di dalam templat
kalau tulisan server-only nggak perlu mas, tapi kalau kata server harus diterjemahkan

2021-02-18 16:56 UTC, febrihidayan commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
bisa diartikan: Menyesuaikan lokasi ini mungkin diperlukan jika proyek diatur sebagai ruang kerja Yarn dengan mono-repositori.

2021-02-18 17:01 UTC, fajarafriansh commented on content/id/guides/directory-structure/nuxt-config.md
> +Setting this field may be necessary if your project is organized as a Yarn workspace-styled mono-repository.
baik mas, terima kasih 👍

2021-02-18 17:39 UTC, febrihidayan commented
@fajarafriansh Oke, Mas. ditunggu satu berkas lagi 👏

2021-02-18 17:46 UTC, fajarafriansh commented
> @fajarafriansh Oke, Mas. ditunggu satu berkas lagi 👏

siap mas 👍

oh iya mas, misal mau memperbaiki typo di file yang telah selesai diterjemahkan, PR-nya ke Issue ini juga atau langsung aja?

2021-02-19 04:26 UTC, febrihidayan commented
Bisa saja mas secara langsung biar jadi satu request 👍

2021-02-24 06:03 UTC, fajarafriansh commented
Maaf mas @febrihidayan, commit-nya lama. Banyak pekerjaan lain yang harus dilakukan, jadi penerjemahan ini harus ditinggalkan.

2021-02-24 06:16 UTC, febrihidayan commented
@fajarafriansh oke mas, nggak apa apa 👏

2021-02-26 17:21 UTC, jefrydco requested changes
Btw `modules.md` udah diterjemahkan di PR ini https://github.com/nuxt/nuxtjs.org/pull/1169/files

cc: @R1dwanMaulana

2021-02-27 03:47 UTC, febrihidayan commented
@jefrydco, saya baru sadar mas @R1dwanMaulana  lebih dulu melakukan PR. Mungkin ada saran untuk kedua PR tersebut mana yang akan di pakai?

2021-02-28 10:51 UTC, jefrydco commented
@febrihidayan Kalau menurut saya menggunakan PR dari Mas @R1dwanMaulana ajah. PR dari mas Ridwan duluan dan sana sudah banyak reviewnya.

2021-02-28 11:36 UTC, febrihidayan commented
@fajarafriansh Apakah bisa menghapus berkas modules.md pada commit sebelumnya?

2021-02-28 12:15 UTC, fajarafriansh commented
> @fajarafriansh Apakah bisa menghapus berkas modules.md pada commit sebelumnya?

bisa mas

2021-02-28 12:38 UTC, febrihidayan approved these changes

2021-02-28 12:38 UTC, merged