Numerous translation fixes for homepage in Bahasa Indonesia.
nuxt/nuxtjs.org pull request #1297
Opened 2021-03-02 02:37 UTC by danilhendrasr

2021-03-07 09:29 UTC, jefrydco requested changes
Mas @danilhendrasr minta tolong judulnya diberi prefix ya, kurang lebih seperti ini:

`docs(id): numerous translation fixes for homepage in Bahasa Indonesia`

2021-03-07 09:29 UTC, jefrydco commented on i18n/id-ID.js
> +      'Jumpa kesalahan atau ingin berkontribusi pada posting blog ini?'
```suggestion
      'Menemukan kesalahan atau ingin berkontribusi pada _postingan_ blog ini?'
```

2021-03-07 09:29 UTC, jefrydco commented on i18n/id-ID.js
> +      '{team} kami sekarang menawarkan layanan konsultasi resmi untuk aplikasi NuxtJS Anda. {Break} Kami menawarkan layanan berbeda tergantung kebutuhan Anda, dari dukungan teknis hingga pengembangan
```suggestion
      '{team} kami sekarang menawarkan layanan konsultasi resmi untuk aplikasi NuxtJS Anda. {Break} Kami menawarkan layanan berbeda tergantung kebutuhan Anda, dari dukungan teknis hingga pengembangan kustom. Anda dapat mengharapkan balasan dalam satu hari kerja, kami dapat menandatangani Perjanjian Larangan Pengungkapan Informasi Rahasia (_Non-Disclosure Agreement_) khusus dan Anda bisa mendapatkan pengembalian dana penuh jika Anda tidak puas dengan layanan kami.',
```

2021-03-07 09:29 UTC, jefrydco commented on i18n/id-ID.js
> +        sponsorNuxt: 'Donasi dan menjadi sponsor'
```suggestion
        sponsorNuxt: 'Donasi dan Menjadi Sponsor'
```

2021-03-07 09:29 UTC, jefrydco commented on i18n/id-ID.js
> +      title: 'Kerangka Kerja {br} {frameworkType} yang Intuitif',
Slogan Vue.js berbahasa Indonesia, "Kerangka Kerja JavaScript nan Progresif". Mungkin untuk menjaga kekonsistensian, menurut saya slogan untuk Nuxt.js berbasa Indonesia berikut yang cocok:

```suggestion
      title: 'Kerangka Kerja {br} {frameworkType} nan Intuitif',
```

2021-03-07 09:44 UTC, febrihidayan commented on i18n/id-ID.js
> +      'Jumpa kesalahan atau ingin berkontribusi pada posting blog ini?'
Kenapa postingan dibuat miring, mas?

2021-03-07 09:55 UTC, jefrydco commented on i18n/id-ID.js
> +      'Jumpa kesalahan atau ingin berkontribusi pada posting blog ini?'
Karena saya mencoba mencarinya di beberapa dokumen di sini https://github.com/frontend-id/glosarium#sumber-terjemahan-lain tidak menemukan kata "postingan". Biasanya kata bahasa Indonesia yang tidak baku akan dicetak miring.

2021-03-07 12:04 UTC, danilhendrasr commented
> Mas @danilhendrasr minta tolong judulnya diberi prefix ya, kurang lebih seperti ini:
> 
> `docs(id): numerous translation fixes for homepage in Bahasa Indonesia`
> 
> cc: @febrihidayan

Wah maaf maaf, will do for the next PRs.

2021-03-07 13:46 UTC, febrihidayan commented on i18n/id-ID.js
> +      'Jumpa kesalahan atau ingin berkontribusi pada posting blog ini?'
Kalau bisa ada kata yang baku seputar pos -> mengeposkan dan pengeposan

Jadi `pada pengeposan blog ini?`

2021-03-08 15:38 UTC, jefrydco commented on i18n/id-ID.js
> +      'Jumpa kesalahan atau ingin berkontribusi pada posting blog ini?'
Sounds good 👍🏼

2021-03-08 16:39 UTC, febrihidayan commented
@jefrydco Apakah sudah siap LGTM?

2021-03-09 02:11 UTC, jefrydco approved these changes
Nice work! 🎉

2021-03-09 12:12 UTC, febrihidayan approved these changes

2021-03-09 12:12 UTC, merged