Support Qovery as a deployment option
nuxt/nuxtjs.org pull request #1352
Opened 2021-03-18 14:56 UTC by arnaudjnn

Hi Nuxt.js team,

I added docs on deploying Nuxt.js to Qovery - feedback is welcome.

Arnaud.

2021-03-18 20:51 UTC, danielroe commented on content/en/guides/deployment/deployment-qovery.md
> +target: Server
should this be Static & Server?
```suggestion
target: Static & Server
```

2021-03-18 20:51 UTC, danielroe commented on content/en/guides/deployment/deployment-qovery.md
> +This guide assumes you already have a Nuxt project to deploy. If you need a project, use the [Get Started](/content/en/get-started/installation.md).
```suggestion
This guide assumes you already have a Nuxt project to deploy. If you need a project, follow the [Get Started](/content/en/get-started/installation.md) guide.
```

2021-03-26 16:52 UTC, danielroe requested changes
Just picking up on this again - looks great, just needs a few tweaks.

2021-03-27 20:43 UTC, evoxmusic commented
Hi @danielroe , @arnaudjnn will apply your changes on Monday :)

2021-03-29 13:38 UTC, arnaudjnn commented
> Just picking up on this again - looks great, just needs a few tweaks.

I made the changes as required. Let me know

2021-04-01 19:38 UTC, danielroe commented on content/en/guides/deployment/deployment-qovery.md
> +This guide assumes you already have a Nuxt project to deploy. If you need a project, follow the [Get Started](/content/en/get-started/installation.md) guide.
```suggestion
This guide assumes you already have a Nuxt project to deploy. If you need a project, follow the [Get Started](/docs/2.x/get-started/installation) guide.
```

2021-04-01 19:39 UTC, danielroe commented on content/en/guides/deployment/deployment-qovery.md
> +Follow the procedure below to set up a Nuxt on Qovery:
```suggestion
Follow the procedure below to set up Nuxt on Qovery:
```

2021-04-01 19:40 UTC, danielroe approved these changes

2021-05-04 09:40 UTC, merged