【WIP】docs(ja): update configuration-glossary/configuration-build
nuxt/nuxtjs.org pull request #1407
Opened 2021-04-25 13:21 UTC by Katakuranatsumi

resolve vuejs-jp#249

2021-04-26 12:30 UTC, inouetakuya requested changes
Thank you for your PR 👍

2021-04-26 12:30 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-build.md
> +> インラインサーバーバンドルの依存関係（詳細）
「詳細」と書かれていると、詳細情報へのリンクかなと誤読させてしまうかもしれないので、違う言葉にしたいですね。

代案は... うーん... 🤔

2021-04-26 12:30 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-build.md
> +<base-alert type="warning">\*_Warning_: ランタイムの依存関係（モジュール、`nuxt.config`、サーバーミドルウェア、静的ディレクトリ）はバンドルされていません。この機能は、server-bundle での[webpack-externals](https://webpack.js.org/configuration/externals/)の使用のみ
```suggestion
<base-alert type="warning">\*_Warning_: ランタイムの依存関係（モジュール、`nuxt.config`、サーバーミドルウェア、静的ディレクトリ）はバンドルされていません。この機能は、server-bundle での [webpack-externals](https://webpack.js.org/configuration/externals/) の使用のみを無効にします。</base-alert>
```

2021-04-26 12:30 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-build.md
> +> インラインサーバーバンドルの依存関係（詳細）
https://github.com/nuxt/nuxtjs.org/blob/92b245891ff4f783eb17378f440bebb5d7605d64/i18n/ja-JP.js#L306 では「上級」という言葉が遣われているのですが、うーん、あくまで案ですが、「アドバンスド」とそのまま書いた方が伝わる気がしました。

2021-04-26 12:30 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-build.md
> +> インラインサーバーバンドルの依存関係（詳細）
「インラインサーバーバンドルの依存関係」の箇所の原文は「Inline server bundle dependencies」なのですが、これは「This mode bundles `node_modules` that are normally preserved as externals in the server build」と同じ意味合いなので、そのあたりがもう少し伝わる訳にしたいですね。

とはいえ難しい... 代案は... うーん... 🤔

2021-04-26 12:30 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-build.md
> +> インラインサーバーバンドルの依存関係（詳細）
あくまで案ですが、

```suggestion
> サーバービルドにおいて依存関係をインラインでバンドル（アドバンスド）
```

とか、どうでしょう？日本語と英語の混ぜこぜで若干気持ち悪いですが... 💦

2021-04-26 14:03 UTC, Katakuranatsumi commented on content/ja/guides/configuration-glossary/configuration-build.md
> +> インラインサーバーバンドルの依存関係（詳細）
ご確認ありがとうございましたmm

>「詳細」と書かれていると、詳細情報へのリンクかなと誤読させてしまうかもしれないので、違う言葉にしたいですね。

仰る通り、「詳細」だとリンクがあるものだと読み取ってしまう方が多そうですね💦
(少し考えたのは、`詳細`を`上級者向け`に変更する、という案ですmm)

> 「インラインサーバーバンドルの依存関係」の箇所の原文は「Inline server bundle dependencies」なのですが、これは「This mode bundles node_modules that are normally preserved as externals in the server build」と同じ意味合いなので、そのあたりがもう少し伝わる訳にしたいですね。

>サーバービルドにおいて依存関係をインラインでバンドル（アドバンスド）

ご提案ありがとうございます。はい、ご提案いただいた案の翻訳の方が分かりやすいと思います🙇‍♀️
ご提案いただいた案で cbd7a15 で修正しましたmm

2021-04-26 14:04 UTC, Katakuranatsumi commented on content/ja/guides/configuration-glossary/configuration-build.md
> +<base-alert type="warning">\*_Warning_: ランタイムの依存関係（モジュール、`nuxt.config`、サーバーミドルウェア、静的ディレクトリ）はバンドルされていません。この機能は、server-bundle での[webpack-externals](https://webpack.js.org/configuration/externals/)の使用のみ
こちらリンクの両端にスペースを入れておらず失礼しました🙇‍♀️
72bccdf で修正しましたmm

2021-04-27 01:59 UTC, inouetakuya approved these changes
LGTM, thank you! 👍 👍 👍

2021-04-27 01:59 UTC, merged