docs(fr): new version 3 translation
nuxt/nuxtjs.org pull request #1542
Opened 2021-07-16 07:27 UTC by Geminii

_Nuxt3 page :_
- [x] nuxt3 coming soon

2021-07-16 08:29 UTC, Atinux commented on content/fr/v3.md
> +Nuxt 3 amène les applications web à un nouveau niveau, rendu hybride statique et serveur, routes API, sans serveur.
Je pense pas que serverless se traduit en "sans serveur"

2021-07-16 08:33 UTC, Geminii commented on content/fr/v3.md
> +Nuxt 3 amène les applications web à un nouveau niveau, rendu hybride statique et serveur, routes API, sans serveur.
Yes, il ne se traduit pas. Je l'ai déjà corrigé dans ma nouvelle version qui arrive :)

2021-07-19 09:48 UTC, clemcode requested changes

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/6.loading/2.customize-loading-indicator.md
> +title: Personnaliser l'indacteur de chargement de Nuxt
```suggestion
title: Personnaliser l'indicateur de chargement de Nuxt
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/7.miscellaneous/2.lazy-loading-components.md
> +description: Utilisez fetch dans vos composants pour récupérer des données à partir d'une API ainsi que d'importer automatiquement vos composants et de chargement différé.
```suggestion
description: Utilisez fetch dans vos composants pour récupérer des données à partir d'une API ainsi qu'importer automatiquement vos composants en chargement différé.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/7.miscellaneous/2.lazy-loading-components.md
> +Utilisez fetch dans vos composants pour récupérer des données à partir d'une API ainsi que d'importer automatiquement vos composants et de chargement différé.
```suggestion
Utilisez fetch dans vos composants pour récupérer des données à partir d'une API ainsi qu'importer automatiquement vos composants en chargement différé.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/1.router.md
> +title: Routeur de middleware
```suggestion
title: Middleware de routage
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/1.router.md
> +# Routeur de middleware
```suggestion
# Middleware de routage
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/1.router.md
> +description: Utiliser un middleware de routeur pour définir une classe pour le corps afin que nous puissions ensuite le styliser différemment en fonction de la route.
```suggestion
description: Utilisez un middleware de routage pour définir une classe pour le corps afin que nous puissions ensuite le styliser différemment en fonction de la route.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/1.router.md
> +Utiliser un middleware de routeur pour définir une classe pour le corps afin que nous puissions ensuite le styliser différemment en fonction de la route.
```suggestion
Utiliser un middleware de routage pour définir une classe pour le corps afin que nous puissions ensuite le styliser différemment en fonction de la route.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/1.router.md
> +`middleware/class.js` utilise un middleware de routeur pour définir une classe avant d'entrer dans la route.
```suggestion
`middleware/class.js` utilise un middleware de routage pour définir une classe avant d'entrer dans la route.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/2.named.md
> +title: Middleware nommés
```suggestion
title: Middleware nommé
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/1.examples/8.middlewares/2.named.md
> +# Middleware nommés
```suggestion
# Middleware nommé
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/3.resources/video-courses.md
> +    description: Une liste de lecture de vidéos YouTube couvrant tout ce qui concerne Nuxt, y compris de courtes vidéos et des flux en direct.
```suggestion
    description: Une liste de lecture de vidéos YouTube couvrant tout ce qui concerne Nuxt, y compris de courtes vidéos et des livestreams.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/v3.md
> +  description: Bêta privée pour l'équipe principale de Vue et les auteurs de modules Nuxt.
```suggestion
  description: Bêta privée pour l'équipe core de Vue et les auteurs de modules Nuxt.
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/v3.md
> +  description: "L'application Nuxt 3 par défaut est de 13 Ko, soit une réduction de 20% par rapport à Nuxt 2."
```suggestion
  description: "L'application Nuxt 3 pèse par défaut 13 Ko, soit une réduction de 20% par rapport à Nuxt 2."
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/v3.md
> +  description: 'Démarrage du serveur et temps de réponse plus rapides grâce au fractionnement de code, optimisé par h3.'
```suggestion
  description: 'Démarrage du serveur et temps de réponse plus rapides grâce au code-splitting, optimisé par h3.'
```

2021-07-19 09:48 UTC, clemcode commented on content/fr/v3.md
> +  description: "La génération statique incrémentielle est désormais possible, spécifiez vos pages statiques et laissez Nuxt s'occuper du reste."
```suggestion
  description: "La génération statique incrémentale est désormais possible, spécifiez vos pages statiques et laissez Nuxt s'occuper du reste."
```

2021-07-19 14:34 UTC, clemcode commented on content/fr/v3.md
> +  En production, il construit votre application et votre serveur dans un répertoire universel `.output`. Cette **sortie est légère** : minimisée et supprimée de tous les modules de node (attendez les
```suggestion
  En production, il construit votre application et votre serveur dans un répertoire universel `.output`. Cette **sortie est légère** : minimisée et supprimée de tous les modules de node (excepté les polyfills). Vous pouvez déployer cette sortie sur n'importe quel système prenant en charge JavaScript, à partir de Node, Serverless, Workers, Edge-side Rendering ou purement statique.
```

2021-07-22 08:59 UTC, clemcode approved these changes
👍

2021-07-22 08:59 UTC, merged