[Translation] German
nuxt/nuxtjs.org pull request #1774
Opened 2021-09-22 19:15 UTC by Intevel

Hello,
I am not completely finished yet, the following translations are missing:

 /integrations/
 /announcements/2.understanding-how-fetch-works-in-nuxt-2-12.md/
 /docs/
 
 I don't think I forgot anything, otherwise everything should be translated. i'm working on the rest of the translation.

2021-09-23 10:49 UTC, Intevel commented
Hey @smarroufin , of course, I'll keep working on the rest of the translation, is there any way to be notified when you can translate new stuff again? And I thought that I had translated `i18n/de-DE.js` completely, I will fix that right now.

2021-09-23 10:51 UTC, Intevel commented
I updated it

2021-09-23 11:02 UTC, Intevel commented
Are the translations marked only when they are complete or before? Because in the i18n are many files, but on nuxtjs.org are only 3 languages current.

2021-09-23 11:59 UTC, Intevel commented
okay and when geht it merged? @smarroufin

2021-09-23 17:02 UTC, manniL requested changes
First of all - thanks for your work!

I started the review on a quite fine-grained level. While most of the content (which I've read so far) seems fine, some translations sound too artificial and sometimes there are inconsistencies as well as a mix of German and English.

Please take a look at my comments and review your translated files with regards to the mentioned issues. Then, I'll have another closer look ☺️ 

Nevertheless - great job so far!

2021-09-23 17:02 UTC, manniL commented on content/de/announcements/1.going-full-static.md
> +Beachten Sie, dass es möglich war, vollen Static Support mit dem [nuxt-payload-extractor](https://github.com/DreaMinder/nuxt-payload-extractor) Modul zu haben, aber es war ausführlicher zu benutzen u
"ausführlicher zu benutzten" -> Komische Übersetzung

2021-09-23 17:34 UTC, Intevel commented on content/de/announcements/0.nuxt-static-improvements.md
> +Mit Nuxt v2.13 haben wir `nuxt export` und `nuxt serve` eingeführt, die speziell für Static Targets entwickelt wurden. Mit Nuxt v2.14 sind sie veraltet, da `nuxt generate` und `nuxt start` das Ziel i
Ähnlich wie der Kommentar darüber, ich finde kein vergleichbares Wort dazu weswegen ich über all builden bzw. Build geschrieben habe.

2021-09-23 17:42 UTC, Intevel commented on content/de/announcements/1.going-full-static.md
> +Auch die Erfahrung der Entwickler ist nicht optimal:
DX = Developer Experience
Wie soll ich das übersetzten? Experience bedeutet übersetzt ua. Erfahrung, Erlebnis klingt nicht so gut.

2021-09-23 17:56 UTC, manniL commented on content/de/announcements/1.going-full-static.md
> +Auch die Erfahrung der Entwickler ist nicht optimal:
Einfach so lassen, ähnlich wie "User Experience"

2021-09-23 21:03 UTC, marvin-j97 commented on content/de/announcements/1.going-full-static.md
> +- [Zusammenfasung](#too-long-to-read)
```suggestion
- [Zusammenfassung](#too-long-to-read)
```

2021-09-24 08:53 UTC, Intevel commented on content/de/announcements/0.nuxt-static-improvements.md
> +- Generate dist (`dist/`)
@manniL

2021-09-24 12:02 UTC, marvin-j97 commented on content/de/announcements/1.going-full-static.md
> +[Newsletter abonieren](#subscribe-to-newsletter) um die nächsten Artikel und Ressourcen nicht zu verpassen.
```suggestion
[Newsletter abonnieren](#subscribe-to-newsletter) um die nächsten Artikel und Ressourcen nicht zu verpassen.
```

2021-10-03 14:06 UTC, marvin-j97 commented on content/de/examples/8.middlewares/2.named.md
> +title: Bennante Middleware
```suggestion
title: Benannte Middleware
```

2021-10-03 14:09 UTC, marvin-j97 commented on content/de/examples/7.miscellaneous/2.lazy-loading-components.md
>  description: Verwenden Sie Fetch in Ihren Komponenten, um Daten von einer API abzurufen, sowie für den automatischen Import und das langsame Laden von Komponenten.
Lazy != langsam

2021-12-23 18:13 UTC, danimajo approved these changes
LGTM

2021-12-23 18:18 UTC, danimajo approved these changes

2022-01-18 13:07 UTC, smarroufin commented
Discussed with nuxtlabs team and finally approved. Let's start with this and merge this PR!
Future updates will be easier and smoother :slightly_smiling_face: 
Thanks for your contributions guys! :green_heart:

2022-01-18 13:11 UTC, smarroufin commented
My bad, there are still requested changes :grimacing: 
@manniL can you approve the PR or eventually commit suggested changes please?

2022-01-20 13:40 UTC, manniL commented
Will do ☺️

2023-02-20 10:48 UTC, closed without merging