translation(pt-br): Translate half of the features section
nuxt/nuxtjs.org pull request #2022
Opened 2022-03-01 14:44 UTC by felipesuri

Continuing Portuguese Brazil translation of the docs. (#1987)

- [x] Translate half of the features section.

## Translated pages:

- [x] 1.rendering-modes
- [x] 2.deployment-targets
- [x] 3.file-system-routing
- [x] 4.data-fetching

2022-03-01 15:56 UTC, smarroufin requested changes
Nice work, thanks! 💚 

LGTM except those 2 typos.
Also waiting for @ChristopheCVB approval.

2022-03-01 15:56 UTC, smarroufin commented on content/pt-br/docs/3.features/1.rendering-modes.md
> +Você não precisa adicionar `srr: true` em sua configuração do Nuxt para habilitar a renderização do lado do servidor, pois ela é habilitada por padrão.
```suggestion
Você não precisa adicionar `ssr: true` em sua configuração do Nuxt para habilitar a renderização do lado do servidor, pois ela é habilitada por padrão.
```

2022-03-01 15:56 UTC, smarroufin commented on content/pt-br/docs/3.features/4.data-fetching.md
> +Você pode utilizar a diretiva `keep-alive` nos componentes `<nuxt />` e `</nuxt-child>` para salvar as chamadas ao `fetch` em páginas que você visitou.
```suggestion
Você pode utilizar a diretiva `keep-alive` nos componentes `<nuxt />` e `<nuxt-child />` para salvar as chamadas ao `fetch` em páginas que você visitou.
```

2022-03-02 08:18 UTC, ChristopheCVB requested changes
Just some typos to fix

2022-03-02 08:18 UTC, ChristopheCVB commented on content/pt-br/docs/2.concepts/1.views.md
> +Consulte [Estrutura de Diretório](/docs/directory-structure/pages) para aprender mais sobre todas as propriedades que podem ser utilizadas na sua página.
You sure this is the right link?

2022-03-02 08:18 UTC, ChristopheCVB commented on content/pt-br/docs/3.features/2.deployment-targets.md
> +- Remove `req` e `red` do `context`
```suggestion
- Remove `req` e `res` do `context`
```

2022-03-04 22:32 UTC, felipesuri commented
Done @ChristopheCVB and @smarroufin.

2022-03-05 09:12 UTC, ChristopheCVB approved these changes
👍 Terrific work, again!

2022-03-07 10:31 UTC, smarroufin approved these changes
Thanks again! 💚

2022-03-07 10:33 UTC, merged