docs(pt): add `_collections` translated
nuxt/nuxtjs.org pull request #2072
Opened 2022-05-03 03:20 UTC by nazarepiedady

In this pull request, I am sending the `_collections` translated.

I remember that one day @smarroufin said that have the whole
`pt/docs/` folder translated would be enough to generate a new
website build putting the Portuguese version of the documentation
available, but I would like to ask you for a little 🙏 patience because
I am almost finished translating all files in the `pt/` folder 😊.

With this pull request, it will only be missing the following folders:

- `pt/announcements/`: it being translated.
- `pt/case-studies/`: it being translated.
- `pt/contribution-guide/`: the only file there is already translated.
- `pt/tutorials`: the translation has not started yet.

One more thing 😊,
@smarroufin what kind of contribution someone should do to be here [nuxt.org/teams](https://nuxtjs.org/teams) in the community section?

@smarroufin and @ChristopheCVB it is your turn.

2022-05-03 09:08 UTC, ChristopheCVB requested changes
Just a little typo, thanks for your hard work!

2022-05-03 09:42 UTC, smarroufin commented
Hey @nazarepiedady thanks again for all the work! :green_heart: 

:warning: before you go furthermore into your translations, `announcements/` and `case-studies/` are not meant to be translated. See them as blog articles. Sorry, this is not obvious and we will eventually do something to warn contributors about that.

`_collections` will be enough to enable `pt` language, simplifying reviews with the deploy preview. And you will still be able to translate `contribution-guide/` and `tutorials/` freely.

I'm gonna see about the contributors page and will come back to you :slightly_smiling_face:

2022-05-03 09:55 UTC, smarroufin requested changes

2022-05-03 09:55 UTC, smarroufin commented on content/pt/_collections/teams/2.community.md
> +  -
You can revert this file, no need to change this.

2022-05-03 09:55 UTC, smarroufin commented on content/pt/_collections/testimonials/index.md
> +    testimonial: 'A Nuxt oferece uma solução convincente e um excelente ecossistema para ajudar você a entregar aplicações Vue completas que são funcionais e amigáveis ao SEO. A flexibilidade para es
Testimonials should not be translated. Those sentences are quotes of their author and must not be translated or altered in any ways.

2022-05-04 12:28 UTC, smarroufin commented
@nazarepiedady I discussed the contributors page update with some people. This page will disappear very soon, so we won't update it to delete it right after.

2022-05-04 13:43 UTC, ChristopheCVB approved these changes

2022-05-04 13:47 UTC, merged