docs(pt): add `content/pt/index.md` translated
nuxt/nuxtjs.org pull request #2075
Opened 2022-05-05 21:16 UTC by nazarepiedady

In this commit, I am sending the `index.md` that is in the `pt` root folder.

@smarroufin and @ChristopheCVB your turns 😊.

2022-05-06 09:22 UTC, smarroufin requested changes

2022-05-06 09:22 UTC, smarroufin commented on content/pt/index.md
> +  category: Agência
`category` prop must not be translated

2022-05-30 09:14 UTC, smarroufin commented
@ChristopheCVB Could you review this please? 🙏

2022-05-30 15:57 UTC, ChristopheCVB approved these changes
👍 Tip-Top!

2022-06-01 12:05 UTC, merged