docs(pt): add `tutorials/creating-a-nuxt-module.md` translated
nuxt/nuxtjs.org pull request #2122
Opened 2022-08-20 00:16 UTC by nazarepiedady

Hello fellows, in this pull request, I am sending the translation of
the article `creating a nuxt module`, the rest will come and also
there will be updates for the already translated content.

I am counting on you @smarroufin and @ChristopheCVB.

2022-08-29 14:03 UTC, smarroufin requested changes
The rest looks good, waiting for Christophe for protuguese approval

2022-09-01 02:47 UTC, nazarepiedady commented on content/pt/tutorials/0.creating-a-nuxt-module.md
> +- [Como isto funciona?](#how-does-it-work)
@smarroufin the updates were already made.

Now the only thing that rest is the review of our
colleague @ChristopheCVB.

2022-09-01 09:06 UTC, smarroufin approved these changes

2022-09-01 22:46 UTC, ChristopheCVB approved these changes

2022-09-02 08:46 UTC, merged