[docs-id] Translate guides/features
nuxt/nuxtjs.org pull request #631
Opened 2020-09-01 15:37 UTC by burhanahmeed

Helping docs translation based on this issue #549 
https://github.com/nuxt/nuxtjs.org/issues/549#issuecomment-683523944

:memo: guides -> features

- [ ] configuration.md
- [ ] data-fetching.md

2020-09-02 01:07 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Nuxt.js akan secara otomatis menebak berkas berdasarkan jenis extensi berkas dan menggunakan pemuat _pre-processor_ yang pantas untuk _webpack_. Anda masih harus memasang pemuat yang dibutuhkan jika
```suggestion
Nuxt.js akan secara otomatis menebak berkas berdasarkan jenis ekstensi berkas dan menggunakan pemuat _pre-processor_ yang pantas untuk _webpack_. Anda masih harus memasang pemuat yang dibutuhkan jika Anda akan menggunakan mereka.
```

2020-09-02 01:08 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Nuxt.js mengijinkan Anda untuk mendefinisikan berkas/modul/pustaka yang ingin Anda setel secara _global_ (termasuk setiap halaman).
```suggestion
Nuxt.js mengizinkan Anda untuk mendefinisikan berkas/modul/pustaka yang ingin Anda setel secara _global_ (termasuk setiap halaman).
```

2020-09-02 01:09 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +  - question: Apa berkas yang dipanggil untuk mengabaikan berkas di Nuxt.js
```suggestion
  - question: Apa berkas yang dipanggil untuk mengabaikan berkas di Nuxt.js?
```

2020-09-02 01:11 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang _webpack loaders_:
Untuk ini gimana kalau diubah menjadi 
```suggestion
Untuk menggunakan _pre-processors_ ini, kita perlu memasang beberapa _loader webpack_:
```

2020-09-02 01:12 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Anda dapat menggunakan `.nuxtignore` untuk mengizin kan Nuxt.js mengabaikan berkas `layout`, `page`, `store` and `middleware` pada dasar direktori proyek (`rootDir`) ketika fase _build_. berkas `.nux
```suggestion
Anda dapat menggunakan `.nuxtignore` untuk mengizinkan Nuxt.js mengabaikan berkas `layout`, `page`, `store` and `middleware` pada dasar direktori proyek (`rootDir`) ketika fase _build_. berkas `.nuxtignore` merujuk pada spesifikasi yang sama seperti berkas `.gitignore` dan `.eslintignore`, di mana setiap baris adalah sekumpulan pola yang menunjukkan berkas mana yang harus diabaikan.
```

2020-09-02 01:15 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Dapat lebih dikustom daripada _ignorePrefix_: semua berkas yang cocok dengan sekumpulan pola yang dispesifikasikan didalam _ignore_ akan diabaikan ketika proses _build_.
Untuk ini bagaimana kalau diubah jadi:
```suggestion
Lebih dapat dikustomisasi daripada _ignorePrefix_: semua berkas yang cocok dengan sekumpulan pola yang dispesifikasikan didalam _ignore_ akan diabaikan ketika proses _build_.
```

2020-09-02 01:18 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Secara bawaan, server pengembangan Nuxt.js adalah `localhost` yang mana hanya dapat diakses dari dalam mesin tuan rumah. Untuk melihat aplikasi Anda pada perangkat lain, Anda perlu memodifikasi tuan
Menurut saya kata _host_ dalam paragraf ini tidak perlu diterjemahkan menjadi "tuan rumah". Bagaimana menurut anda?

2020-09-02 01:23 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Metode `extend` dipanggil dua kali, pertama untuk membendel klien dan selebihnya untuk membendel server.
Berdasarkan KBBI, kata yang baku adalah "bundel", dan kata kerja aktif nya adalah "membundel". Jadi menurut saya lebih baik jika diubah sesuai demikian
```suggestion
Metode `extend` dipanggil dua kali, pertama untuk membundel klien dan selebihnya untuk membundel server.
```

2020-09-02 02:23 UTC, burhanahmeed commented on content/id/guides/features/configuration.md
> +Metode `extend` dipanggil dua kali, pertama untuk membendel klien dan selebihnya untuk membendel server.
iya bundel yang baku

2020-09-02 02:32 UTC, burhanahmeed commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang _webpack loaders_:
kalau ini baiknya loader ditulis  _loader_ webpack atau ditulis `pemuat` webpack?

2020-09-02 02:49 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang _webpack loaders_:
Menurut saya, karena _loader_ dalam konteks pembicaraan tentang Webpack merupakan istilah teknis, lebih baik tetap menggunakan kata _loader_.

2020-09-02 02:53 UTC, burhanahmeed commented on content/id/guides/features/configuration.md
> +Dapat lebih dikustom daripada _ignorePrefix_: semua berkas yang cocok dengan sekumpulan pola yang dispesifikasikan didalam _ignore_ akan diabaikan ketika proses _build_.
bagian ini saya lebih cocok dengan `Dapat lebih dikustomisasi`

2020-09-02 02:54 UTC, danilhendras commented on content/id/guides/features/configuration.md
> +Dapat lebih dikustom daripada _ignorePrefix_: semua berkas yang cocok dengan sekumpulan pola yang dispesifikasikan didalam _ignore_ akan diabaikan ketika proses _build_.
Baik, saya rasa itu juga bagus.

2020-09-02 02:55 UTC, burhanahmeed commented on content/id/guides/features/configuration.md
> +Secara bawaan, server pengembangan Nuxt.js adalah `localhost` yang mana hanya dapat diakses dari dalam mesin tuan rumah. Untuk melihat aplikasi Anda pada perangkat lain, Anda perlu memodifikasi tuan
_resolved_ di commit terbaru

2020-09-03 00:37 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +  - question: Dimana Anda dapat menggunakan pengait _fetch_ pada Nuxt.js?
```suggestion
  - question: Di mana Anda dapat menggunakan pengait _fetch_ pada Nuxt.js?
```

2020-09-04 15:24 UTC, burhanahmeed commented
Kindly review my works @danilhendras @febrihidayan @jefrydco

2020-09-04 15:27 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +  - question: Apa server pengembangan bawaan dari Nuxt.js?
`server` -> `_server_`

2020-09-04 15:28 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +  - question: Atribut mana yang Anda gunakan pada tag style untuk menggunakan SCSS?
`style` -> `_style_`

2020-09-04 15:30 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Nuxt.js akan secara otomatis menebak berkas berdasarkan jenis ekstensi berkas dan menggunakan pemuat _pre-processor_ yang pantas untuk _webpack_. Anda masih harus memasang pemuat yang dibutuhkan jika
Mas @trastanechora kemaren `webpack` ditulis bagaimana ya?

2020-09-04 15:31 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Contoh dari `pages/index.vue` kami menggunakan [Pug](https://github.com/pugjs/pug) and [Sass](http://sass-lang.com/):
`and` belum di terjemahkan

2020-09-04 15:34 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang beberapa _loader_ Webpack:
Mengacu pada bagian ini https://github.com/nuxt/nuxtjs.org/pull/621#issuecomment-684235896, `_loader_` diterjemahkan menjadi pemuat

2020-09-04 15:34 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Nuxt.js menggunakan [@nuxt/babel-preset-app](https://github.com/nuxt/nuxt.js/tree/dev/packages/babel-preset-app), yang mana berdasarkan ofisial [@vue/babel-preset-app](https://github.com/vuejs/vue-cl
`ofisial` -> `resmi`

2020-09-04 15:35 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Setiap berkas pada `pages/`, `layout/`, `middleware/` atau `store/` akan diabaikan ketika _build_ jika nama berkasnya dimulai dengan _prefix_ yang telah dispesifikasikan di _ignorePrefix_.
`_prefix_` sepertinya bisa dipadankan dengan `awalan`

2020-09-04 15:37 UTC, burhanahmeed commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang beberapa _loader_ Webpack:
bagian ini kemarin juga sempat diskusi dengan mas @danilhendras antara pakai _loader_ atau pemuat

2020-09-04 15:38 UTC, jefrydco commented on content/id/guides/features/data-fetching.md
> +Pengait `fetch` Nuxt.js dipanggil setelah instance komponen dibuat pada sisi peladen (_server_): `this` juga tersedia di dalamnya.
`instance` -> `_instance_`

2020-09-04 15:40 UTC, jefrydco commented on content/id/guides/features/data-fetching.md
> +Anda dapat menggunakan _directive_ `keep-alive` di komponen `<nuxt/>` dan `<nuxt-child/>` untuk menyimpan pemanggilan `fetch` pada halaman yang Anda telah kunjungi:
`_directive_` -> `direktif`

Referensi: https://github.com/vuejs-id/docs/blob/master/GLOSARIUM.md#d

2020-09-04 15:41 UTC, jefrydco commented on content/id/guides/features/configuration.md
> +Untuk menggunakan _pre-processors_ ini, kita perlu memasang beberapa _loader_ Webpack:
Mungkin kalau dirasa kurang familiar bisa ditambah kata aslinya Mas setelah padanannya

2020-09-04 15:42 UTC, danilhendras requested changes

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +`asyncData` hanya dapat digunakan pada [halaman (_pages_)](/guides/directory-structure/pages) dan Anda tidak memiliki akses ke `this` didalam pengait tersebut.
```suggestion
`asyncData` hanya dapat digunakan pada [halaman (_pages_)](/guides/directory-structure/pages) dan Anda tidak memiliki akses ke `this` di dalam pengait tersebut.
```

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Pertama, Kami perlu menginstall ini:
```suggestion
Pertama, kita perlu menginstall ini:
```
Saya rasa kata "_we_" dalam paragraf ini berarti "kita". Tidak seperti kata "_we_" pada paragraf di atasnya yang berarti "kami".

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Pertama, Kami perlu menginstall ini:
Saya rasa kata "menginstall" bukanlah kata kerja yang baku, bagaimana kalau diganti dengan kata "memasang paket ..." atau "meng-_install_" ?

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Pada contoh berikut ini, Kami menggunakan [@nuxt/http](https://http.nuxtjs.org/) yang mana Kami merekomendasikan untuk menggambil data dari _API_.
Saya rasa terjemahan untuk kata _API_ di sini tidak cukup konsisten dengan terjemahan di baris ketiga yang menuliskan "... antarmuka pemrograman aplikasi (_API_) ...".

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +### Memperhatikan pada perubahan kueri
Bagaimana kalau seperti ini?
```suggestion
### Memperhatikan perubahan pada kueri
```

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Setiap kali Anda harus mengambil data asinkron, `fetch` dipanggil pada sisi peladen (_server_) ketika me-_render_ rute dan pada sisi klien ketika menggunakan navigasi.
Merujuk pada KBBI, kata "server" ternyata ada. Jadi saya rasa tidak perlu diterjemahkan menjadi "peladen".
```suggestion
Setiap kali Anda harus mengambil data asinkron, `fetch` dipanggil pada sisi server ketika me-_render_ rute dan pada sisi klien ketika menggunakan navigasi.
```

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +`fetchOnServer`: `Boolean` atau `Function` (nilai anggapan: `true`), memanggil `fetch()` ketika peladen me-_render_ halaman.
```suggestion
`fetchOnServer`: `Boolean` atau `Function` (nilai anggapan: `true`), memanggil `fetch()` ketika server me-_render_ halaman.
```

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Ketika `fetchOnServer` bernilai salah (`false` atau mengembalikan `false`), `fetch` akan dipanggil hanya pada sisi klien dan `$fetchState.pending` akan mengembalikan `true` ketika peladen me-_render_
```suggestion
Ketika `fetchOnServer` bernilai salah (`false` atau mengembalikan `false`), `fetch` akan dipanggil hanya pada sisi klien dan `$fetchState.pending` akan mengembalikan `true` ketika server me-_render_ komponen.
```

2020-09-04 15:42 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Pengait `fetch` tidak dipanggil pada perubahan untaian kueri pada dasarnya. Untuk melakukan _watch_ untuk perubahan kueri, Anda dapat menambahkan _watcher_ pada `$route.query` dan memanggil `$fetch`:
```suggestion
Pada dasarnya, pengait `fetch` tidak dipanggil pada perubahan untaian kueri. Untuk melakukan _watch_ untuk perubahan kueri, Anda dapat menambahkan _watcher_ pada `$route.query` dan memanggil `$fetch`:
```

2020-09-04 15:48 UTC, danilhendras commented on content/id/guides/features/data-fetching.md
> +Pengait `fetch` Nuxt.js dipanggil setelah instance komponen dibuat pada sisi peladen (_server_): `this` juga tersedia di dalamnya.
Maaf mas, barusan saya cek di KBBI ternyata ada kata `server`. Apakah masih perlu dipadankan dengan `peladen`?

2020-09-04 15:52 UTC, jefrydco commented on content/id/guides/features/data-fetching.md
> +Pengait `fetch` Nuxt.js dipanggil setelah instance komponen dibuat pada sisi peladen (_server_): `this` juga tersedia di dalamnya.
Kalau menurut Mas @isatrio lebih baik menggunakan `peladen` atau `server`?

2020-09-04 16:46 UTC, febrihidayan approved these changes
Saya sudah coba di lokal, kelihatannya aman-aman saja untuk saat ini

2020-09-05 03:03 UTC, burhanahmeed commented on content/id/guides/features/data-fetching.md
> +Pertama, Kami perlu menginstall ini:
boleh juga `memasang pake`

2020-09-05 03:06 UTC, danilhendras approved these changes

2020-09-05 03:06 UTC, burhanahmeed commented
`server` atau peladen disini saya ubah menjadi _server_ semua

2020-09-05 18:58 UTC, jefrydco commented
Mas @burhanahmeed sebelum di merge, minta tolong commit nya di reset dulu ya biar jadi 1 commit ajah

2020-09-06 14:03 UTC, trastanechora commented on content/id/guides/features/configuration.md
> +Nuxt.js akan secara otomatis menebak berkas berdasarkan jenis ekstensi berkas dan menggunakan pemuat _pre-processor_ yang pantas untuk _webpack_. Anda masih harus memasang pemuat yang dibutuhkan jika
Di dokumen kemarin `webpack` tidak dicetak miring, mengacu pada penggunaan kata `webpack` di situs dokumentasi Vue ini https://docs.vuejs.id/v2/guide/installation.html

2020-09-07 03:27 UTC, jefrydco approved these changes

2020-09-21 10:27 UTC, debs-obrien commented
Thanks for the amazing hard work guys 💪

2020-09-21 10:27 UTC, merged