Translation to Spanish - Nuxt-components.md document
nuxt/nuxtjs.org pull request #694
Opened 2020-09-13 21:17 UTC by FelixMor

Translation of the following document guides/features/nuxt-components.md

2020-09-14 07:03 UTC, debs-obrien commented
@alvarosaburido @Dawntraoz can one of you give this a quick review please

2020-09-14 08:20 UTC, alvarosaburido requested changes
In general, it's a  pretty good translation,  just need to check small things like the English terms inside a Spanish sentence should be italic:  ex,  "Usando el _prefetch_ 

Also,  there is a mix of using the English term `prop` and the Spanish "propiedad", I recommend to chose one, and stick with it the rest of the article to keep consistency.

Great work!

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Para aprender más sobre keep-alive y keep-alive-props, consultar [vue docs](https://vuejs.org/v2/api/#keep-alive)
Para aprender más sobre `keep-alive` y `keep-alive-props`

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Sin embargo, en ciertas circunstancias es probable que desees desactivar el prefetching de algunos hipervínculos, por ejemplo, si tu página tiene mucho JavaScript, si tienes muchas páginas diferentes
_prefetching_

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Para desactivar el prefetching en todos los hipervínculos, fija los `prefetchLinks` en `false`:
Same here and in the title

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Este código en css se puede agregar ya sea al componente de navegación, a una página o layout en particular, o a tu archivo main.css .
Este código css se puede agregar ya sea al componente de navegación, a una página/layout en particular, o a tu archivo main.css .

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +linkPrefetchedClass permite añadir estilos a todos los hipervínculos a que se les haya realizado prefetching. Esto resulta fabuloso para probar a cuáles hipervínculos se les ha realizado prefetching
La opción `linkPrefetchedClass`

2020-09-14 08:20 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Este componente se usa para desplegar un componente del lado del cliente únicamente. Para importar un componente solamente del lado del cliente, registra el componente en un plugin que funcione única
Este componente se usa para desplegar un componente del lado del cliente únicamente. Para importar un componente, registra el componente en un plugin que funcione solamente del lado del cliente

2020-09-14 10:02 UTC, Dawntraoz commented on content/es/guides/features/nuxt-components.md
> +  - question: ¿Qué clase se utiliza por defecto para agregar estilos a hipervínculos activos?
Está todo estupendo, muchas gracias por tu esfuerzo!!
Teniendo en cuenta los comentarios de Álvaro, para tener coherencia con el resto de términos, estaría bien sustituir hipervínculo/s por _link/s_ en todo el documento. No todo el mundo conoce el término traducido y puede llevar a la confusión.
Espero que sirva para que más gente lo entienda!!

2020-09-20 17:58 UTC, FelixMor commented
> @alvarosaburido @Dawntraoz can one of you give this a quick review please

Hi, I've just finished including all the changes you suggested.

(Nuxt-components.md document #694)

2020-09-21 10:22 UTC, debs-obrien commented
Great work everyone. 💪👏

2020-09-21 10:22 UTC, merged