Translate guides directory-structure pages to spanish :pencil:
nuxt/nuxtjs.org pull request #705
Opened 2020-09-15 16:39 UTC by krysal

## Related to #543

Translate the following pages to Spanish (es-ES):

:memo: guides -> directory structure
- [x] content
- [x] store

2020-09-17 09:38 UTC, debs-obrien commented
@alvarosaburido @Dawntraoz if any of you have a chance to review this it would be great, Thanks

2020-09-17 15:27 UTC, alvarosaburido requested changes
@krysal awesome job here, just  some minor adjustments and adding  dots '.' at the end of some paragraphs

2020-09-17 16:41 UTC, krysal commented on content/es/guides/directory-structure/content.md
> +### Recarga en caliente en desarrollo
Justo dudaba si traducir _Hot Reload_, concuerdo en dejarlo en inglés, pero no veo problema con _development_, su traducción es sencilla. Quizás una tercera opinión ayudaría. @Dawntraoz ❔

2020-09-17 16:51 UTC, krysal commented
@alvarosaburido Thanks for your review! I was unsure about adding dots '.' at the end of the paragraphs inside alerts because the English version does not have them. Should we add periods in that version too?

2020-09-17 16:51 UTC, Dawntraoz commented on content/es/guides/directory-structure/content.md
> +### Recarga en caliente en desarrollo
Con **Hot reload** estoy de acuerdo que traducido pierde significado, pero development creo que todos lo usamos como desarrollo en castellano, al menos en las universidades y cursos.
Pero lo más importante es tener coherencia, yo comprobaría que en otros archivos se esté traduciendo a 'desarrollo'.

2020-09-17 17:18 UTC, krysal commented on content/es/guides/directory-structure/content.md
> +### Recarga en caliente en desarrollo
Revisando algunos archivos, para `configuration-glossary/configuration-build.md` por ejemplo, se tradujo tanto "Hot Reload" como "development". En `configuration-glossary/configuration-dev.md` también se traduce "development", así que opto por dejar el primero intacto y traducir el segundo.

Habrá que hacer una revisión posterior para mantener uniforme estos detalles. ¡Gracias a los dos por su colaboración! ✨

2020-09-17 17:22 UTC, alvarosaburido commented
> @alvarosaburido Thanks for your review! I was unsure about adding dots '.' at the end of the paragraphs inside alerts because the English version does not have them. Should we add periods in that version too?

Mmmm true 🤔, I checked them without realizing they were inside of the alerts. Grammatically will be better but yeah not sure anymore.

2020-09-17 17:34 UTC, alvarosaburido commented on content/es/guides/directory-structure/content.md
> +### Recarga en caliente en desarrollo
@Dawntraoz con respecto a lo de _development_, tambien se traduce cuando se usa en el contexto de entornos `env`?  ejemplo: `process.env.NODE_ENV = 'development' `=>  `process.env.NODE_ENV = 'desarrollo' `?

Habría que revisar el "Hot Reload" en `configuration-glossary/configuration-build.md` para dejarlo sin traducir, pero sí, si `desarrollo` estoy de acuerdo de dejarlo traducido. 

Gracias a  ambas por vuestro feedback @krysal Dawntraoz

2020-09-21 10:21 UTC, debs-obrien commented
great work everyone. merging this now. If later any changes are needed we can fix it easily in new issue. Thanks for all your efforts. 💪

2020-09-21 10:21 UTC, merged