[Spanish] translate server-side-rendering.md
nuxt/nuxtjs.org pull request #747
Opened 2020-09-21 23:33 UTC by josewhitetower

2020-09-22 06:35 UTC, debs-obrien commented
This has also been translated here https://github.com/nuxt/nuxtjs.org/pull/751 so perhaps checking this also against the other one and we can merge either of them depending on if need further review etc. cc @alvarosaburido @Dawntraoz

2020-09-23 14:36 UTC, Kronhyx requested changes

2020-09-23 14:36 UTC, Kronhyx commented on content/es/guides/concepts/server-side-rendering.md
> +The browser receives the rendered page El navegador recibe la página renderizada del servidor con el HTML generado. El contenido se muestra y la hidratación del Vue.js se activa, haciéndolo reactivo.
```suggestion
El navegador recibe la página renderizada del servidor con el HTML generado. El contenido se muestra y la hidratación del Vue.js se activa, haciéndolo reactivo. Después de este proceso, la página es interactiva.d HTML.
```

2020-09-28 08:00 UTC, debs-obrien commented
Hi, great work @josewhitetower . As this had also been translated in another pr which is now merged have a look at the conflicts and see if it now makes sense to fix any of the conflicts and merge them or close the pr. Thanks

2020-09-28 08:49 UTC, josewhitetower commented
The merged translation seems great to me, I will close this pr :)

2020-09-28 08:49 UTC, closed without merging