docs(ja): translate guides/features/file-system-routing
nuxt/nuxtjs.org pull request #765
Opened 2020-09-25 02:26 UTC by szk18

@aytdm @inouetakuya @53able 
Hi! I translated `features/file-system-routing.md`. please review this PR✨

**Ref**
- https://github.com/nuxt/nuxtjs.org/issues/544
- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22

2020-10-05 14:38 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +  - question: What is the name of the component you use to navigate between pages?
[docs(ja): translate guides/get-started/conclusion by aytdm · Pull Request #693 · nuxt/nuxtjs.org](https://github.com/nuxt/nuxtjs.org/pull/693/files) あたりを見ると、questions も訳されていたので、questions も翻訳対象かと捉えていました。

が、questions がどこで使われているのか分からないですねえ...

どなたか分かりますか？ > @szk18 @aytdm @53able

2020-10-05 15:17 UTC, inouetakuya requested changes
ひととおり見てコメントを残したので確認をお願いします〜 ☺️

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +ローカルページやコンポーネント内の現在のルートパラメータは、`this.$route.params.{parameterName}` を参照することでアクセスすることができます。例えば、動的なユーザーページ (`users\_id.vue`) があり、ユーザーまたはプロセス情報を読み込むために `id` パラメーターにアクセスしたい場合、次のような変数にアクセスできます: `this.$rout
この `users\_id.vue` って `users/_id.vue` のことだと思うので、en/ もまとめて修正しちゃって、然るべき人にメンション飛ばしておくか、あるいは別プルリクで対応するかしましょうか〜

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +ページ間を遷移するためには [NuxtLink コンポーネント](/guides/features/nuxt-components#the-nuxtlink-component) を使ってください。
他の箇所のアンカーも同様です 📝

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +- [router-extras-module](https://github.com/nuxt-community/router-extras-module)  はページのルートパラメーターをカスタマイズできます
```suggestion
- [router-extras-module](https://github.com/nuxt-community/router-extras-module) を使ってページのルートパラメーターをカスタマイズする
```

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +- [router.extendRoutes](/guides/configuration-glossary/configuration-router#extendroutes)  プロパティを `nuxt.config.js` で使います
```suggestion
- `nuxt.config.js` 内で [router.extendRoutes](/guides/configuration-glossary/configuration-router#extendroutes) プロパティを使う
```

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +- [@nuxtjs/router](https://github.com/nuxt-community/router-module) は独自の `router.js` を使って Nuxt router を上書きすることができます
```suggestion
- [@nuxtjs/router](https://github.com/nuxt-community/router-module) を使い、独自の `router.js` で Nuxt router を上書きする
```

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +Nuxt のルーティングを拡張する方法はいくつかあります:
という記述に続くので、

- 〇〇する（方法）
- 〇〇する（方法）
- 〇〇する（方法）

としたほうが、意味が分かりやすいかと思い、以下代案を書いてみました

2020-10-05 15:17 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +詳細は  [vue-router のスクロールの振る舞いのドキュメント](https://router.vuejs.org/ja/guide/advanced/scroll-behavior.html)を参照してください。
```suggestion
詳細は [vue-router のスクロールの振る舞いのドキュメント](https://router.vuejs.org/ja/guide/advanced/scroll-behavior.html)を参照してください。
```

2020-10-06 04:18 UTC, aytdm commented on content/ja/guides/features/file-system-routing.md
> +  - question: What is the name of the component you use to navigate between pages?
まだ動いてなさそうなんですが、[Quiz コンポーネント](https://github.com/nuxt/nuxtjs.org/blob/master/components/global/bases/Quiz.vue)（このファイルだと L535 で呼ばれている）で使われそうです。 翻訳対象ではありますが、いったんマスト要件からは外していいかなと思って https://github.com/nuxt/nuxtjs.org/pull/619#discussion_r479723900 でやりとりしていました。

2020-10-06 06:34 UTC, inouetakuya commented on content/ja/guides/features/file-system-routing.md
> +  - question: What is the name of the component you use to navigate between pages?
なるほど、把握しました。ありがとうございます！

2020-10-23 05:23 UTC, szk18 commented on content/ja/guides/features/file-system-routing.md
> +ページ間を遷移するためには [NuxtLink コンポーネント](/guides/features/nuxt-components#the-nuxtlink-component) を使ってください。
遅くなってすみません。
https://github.com/nuxt/nuxtjs.org/pull/748#discussion_r492436670 ここで話していたのですが、先に訳しておいたほうが良さそうですね。
おそらく自動でのエンコーディングはしてくれないと思います。(nuxt-components.md で見出しを訳すとこのアンカーリンクは機能しなくなります)

2020-10-23 05:30 UTC, szk18 commented on content/ja/guides/features/file-system-routing.md
> +Nuxt のルーティングを拡張する方法はいくつかあります:
代案ありがとうございます！
こちらのほうがわかりやすいので、採用します🎉

2020-10-23 05:32 UTC, szk18 commented on content/ja/guides/features/file-system-routing.md
> +ローカルページやコンポーネント内の現在のルートパラメータは、`this.$route.params.{parameterName}` を参照することでアクセスすることができます。例えば、動的なユーザーページ (`users\_id.vue`) があり、ユーザーまたはプロセス情報を読み込むために `id` パラメーターにアクセスしたい場合、次のような変数にアクセスできます: `this.$rout
確かに、なぜ気づかなかったんだ、、ありがとうございます！
別プルリクで対応するようにしようと思います

2020-10-24 00:51 UTC, szk18 commented on content/ja/guides/features/file-system-routing.md
> +Nuxt >= 2.13 ではクローラーがインストールされており、リンクタグをクロールしてそれらのリンクに基づいた動的なルートを生成します。しかしシークレットページのようなリンクが存在しないページがある場合、それらの動的なルートは手動で生成する必要があります。
他の箇所の表現もマチマチなので原文に沿ってvをつけます。ありがとうございます👍

2020-10-24 01:05 UTC, szk18 commented
@inouetakuya 
レビューありがとうございます。対応が遅れてすみませんでした。
https://github.com/nuxt/nuxtjs.org/pull/765/commits/216874eecbf5dac29e671e18d8d597f9aedc08a9 でレビューの反映、https://github.com/nuxt/nuxtjs.org/pull/765/commits/5e921727e90db3283c055115f7331ef7350d8d72 でコロンとカッコを全角に変更、vscodeの自動フォーマットで入ったと思われる余計な空白の削除をしました。
お手すきの際に確認お願いします✨

2020-10-24 08:30 UTC, inouetakuya approved these changes
修正を確認しました！LGTM です！おつかれさまでした！！ 👍  👍  👍

2020-10-24 08:43 UTC, merged