Translated guides/concepts/static-site-generation.md to Spanish
nuxt/nuxtjs.org pull request #772
Opened 2020-09-27 01:41 UTC by FelixMor

Translated guides/concepts/static-site-generation.md to Spanish

2020-09-28 07:52 UTC, debs-obrien commented
Hi @FelixMor great work. Can you check your pr and remove all things that shouldn't be there please. You will also have to resolve conflicts. When that is done perhaps @alvarosaburido or @Dawntraoz can give it a quick review. Thanks

2020-09-28 08:21 UTC, debs-obrien commented
Also @FelixMor I just noticed that there is another pr with this file translated. Perhaps you can review this pr and ask for changes in that pr and close this one perhaps. The title of pr says it is for only one file yet 7 files. Always good to keep things as simple as possible. But seen as you have worked on this page it would be great if you could review this https://github.com/nuxt/nuxtjs.org/pull/763 Thanks for the great work

2020-09-28 12:34 UTC, alvarosaburido requested changes
@FelixMor great work, just small changes.

2020-09-28 12:34 UTC, alvarosaburido commented on content/es/guides/concepts/static-site-generation.md
> +      - Cada vez que navegas hacia la página del el contenido de la API
`del` en lugar de `del el`

2020-09-28 12:34 UTC, alvarosaburido commented on content/es/guides/concepts/static-site-generation.md
> +  - question: ¿Qué páginas vuelven al modo de aplicación de página única?
Al ser un término técnico (SPA): 

- ¿Qué páginas vuelven al modo de SPA? 
- ¿Qué páginas vuelven al modo de aplicación de página única (SPA, _single page aplication_)? 

 @Dawntraoz que opinas?

2020-09-28 12:34 UTC, alvarosaburido commented on content/es/guides/features/nuxt-components.md
> +Nuxt.js incluye *smart prefetching* de forma automática. Esto significa que detecta cuando un hipervínculo es visible, ya sea en el viewport o al desplazarse y realiza el *prefetching* en el JavaScri
Nuxt.js incluye *smart prefetching* (precarga inteligente)

2020-09-28 12:34 UTC, alvarosaburido commented on pages/guides/_book/_slug.vue
> +// test comment bla bla bla
Please remove

2020-09-28 12:36 UTC, alvarosaburido commented
> Hi @FelixMor great work. Can you check your pr and remove all things that shouldn't be there, please. You will also have to resolve conflicts. When that is done perhaps @alvarosaburido or @Dawntraoz can give it a quick review. Thanks

Hey @debs-obrien, sorry 😅,  I was on holidays haha, by the way, there are some binary files like `static/blog/build-dev-to-clone-with-nuxt-new-fetch/.dev-clone-nuxt.mp4.icloud `  that shouldn't be there, those are the ones you're referring too?

2020-09-28 18:29 UTC, Kronhyx commented on content/es/guides/concepts/static-site-generation.md
> +      - Cada vez que navegas hacia la página del el contenido de la API
```suggestion
      - Cada vez que navegas hacia la página del contenido de la API
```

2020-09-28 18:31 UTC, Kronhyx commented on content/es/guides/concepts/static-site-generation.md
> +  - question: ¿Qué páginas vuelven al modo de aplicación de página única?
@alvarosaburido Apoyo más la segunda variante.

```suggestion
  - question: ¿Qué páginas vuelven al modo de aplicación de página única (SPA, single page aplication)?
```

2020-09-28 18:31 UTC, Kronhyx commented on content/es/guides/features/nuxt-components.md
> +Nuxt.js incluye *smart prefetching* de forma automática. Esto significa que detecta cuando un hipervínculo es visible, ya sea en el viewport o al desplazarse y realiza el *prefetching* en el JavaScri
```suggestion
Nuxt.js incluye *smart prefetching* (precarga inteligente) de forma automática. Esto significa que detecta cuando un hipervínculo es visible, ya sea en el viewport o al desplazarse y realiza el *prefetching* en el JavaScript para todas aquellas páginas, para que estén listas cuando el usuario da clic al hipervínculo. Nuxt.js solamente carga los recursos cuando el navegador no se encuentra ocupado y no realiza el *prefetching* si tu conexión está offline(fuera de línea) o si solamente tienes conexión 2g.
```

2020-09-28 18:31 UTC, Kronhyx commented on pages/guides/_book/_slug.vue
> +// test comment bla bla bla
```suggestion
```

2020-09-29 18:19 UTC, nilsandrey commented on content/es/guides/features/nuxt-components.md
> +Nuxt.js incluye *smart prefetching* (precarga inteligente) de forma automática. Esto significa que detecta cuando un hipervínculo es visible, ya sea en el viewport o al desplazarse y realiza el *pref
I propose some minor adjustments:

> Nuxt.js incluye precarga inteligente (*smart prefetching*) de forma automática. Esto significa que detecta cuando un hipervínculo es visible, ya sea en el viewport o al desplazarse y realiza la precarga en JavaScript de esa página, para que esté lista cuando el usuario de clic en el hipervínculo. Nuxt.js solamente carga los recursos cuando el navegador no se encuentra ocupado y no realiza la precarga si estás desconectado (offline) o si solamente tienes conexión 2g.

2020-09-30 13:17 UTC, debs-obrien commented
closing this as other pr was merged. please make any further changes in another pr. thanks

2020-09-30 13:17 UTC, closed without merging