docs(ja): translate guides/configuration-glossary/configuration-generate
nuxt/nuxtjs.org pull request #842
Opened 2020-10-14 12:56 UTC by aytdm

@inouetakuya @53able please review this PR.

#### Ref

- https://ja.nuxtjs.org/api/configuration-generate
- https://github.com/nuxt/nuxtjs.org/issues/544
- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22

2020-10-18 06:17 UTC, inouetakuya requested changes

2020-10-18 06:17 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-generate.md
> +ルート生成は並行で行われ、`generate.concurrency` は 1 スレッドで実行されるルートの量を指定します。
[IMO] amount を直訳して量にしたい気持ちも分かりつつ、ルートは数えられるので、ちょっと違和感がありました ☺️ 

```suggestion
ルート生成は並行で行われ、`generate.concurrency` は 1 スレッドで実行されるルートの数を指定します。
```

2020-10-18 06:17 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-generate.md
> +SPA を実行した場合は他のルートが生成されず必要はファイルは `200.html` のみとなるので、`200.html` を使うのが慣用的です。
[IMO] 語句だと慣用的という表現がピッタリくると思うのですが、振る舞いについては慣習的という表現のほうが、しっくり来ます。

https://eow.alc.co.jp/search?q=idiomatic

```suggestion
SPA を実行した場合は他のルートが生成されず必要はファイルは `200.html` のみとなるので、`200.html` を使うのが慣習的です。
```

ただ、あくまで IMO なのでお任せします 🙏

2020-10-18 06:17 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-generate.md
> +2 つのレンダーの間でのインターバルで、ウェブアプリケーションからの潜在的な API に対して溢れでないようにするためのものです
```suggestion
2 つのレンダーの間でのインターバルで、ウェブアプリケーションからの潜在的な API に対して溢れでないようにするためのものです。
```

2020-10-19 15:49 UTC, aytdm commented
ありがとうございます、修正しました

2020-10-20 05:51 UTC, inouetakuya approved these changes
Thank you for your contribution :+1:

2020-10-21 12:30 UTC, debs-obrien commented
@aytdm @inouetakuya I will let you guys go through all the ja prs and see if you can merge the ones you need to and if you come across any issues just let me know. So from now on I will only merge Japanese prs if for some reason you guys can't. Thanks for you fantastic work on contributing and reviewing and getting the new docs translated to Japanese. 😊

2020-10-21 12:48 UTC, aytdm commented
Thank you. You've always been a great support 💚

2020-10-21 12:55 UTC, merged

2020-10-22 02:06 UTC, inouetakuya commented
Thank you so much!! 💚