docs(ja): translate guides/configuration-glossary/configuration-modern
nuxt/nuxtjs.org pull request #859
Opened 2020-10-17 15:01 UTC by aytdm

@inouetakuya @53able please review this PR.

#### Ref

- https://ja.nuxtjs.org/api/configuration-modern
- https://github.com/nuxt/nuxtjs.org/issues/544
- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22

2020-10-18 11:49 UTC, inouetakuya approved these changes
あ、間違えて Approve してしまいました！ :pray:  

1箇所、細かいですが修正お願いします！

2020-10-18 11:49 UTC, inouetakuya commented on content/ja/guides/configuration-glossary/configuration-modern.md
> +    - `'client'`: モダンバンドル `<script type="module">` とレガシーバンドル`<script nomodule>` スクリプトの両方を提供し、モダンバンドル用の `<link rel="modulepreload">` も提供します。`module` タイプを理解するすべてのブラウザではモダンバンドルをロードしますが、古いブラウザではレガシー（トランス
👁️ 

```suggestion
    - `'client'`: モダンバンドル `<script type="module">` とレガシーバンドル `<script nomodule>` スクリプトの両方を提供し、モダンバンドル用の `<link rel="modulepreload">` も提供します。`module` タイプを理解するすべてのブラウザではモダンバンドルをロードしますが、古いブラウザではレガシー（トランスパイルされた）バンドルにフォールバックします。
```

2020-10-18 11:51 UTC, inouetakuya requested changes
誤って Approve してしまったため 🙏

2020-10-19 15:50 UTC, aytdm commented
ありがとうございます。修正しました

2020-10-20 05:43 UTC, inouetakuya approved these changes
Thank you!! 👍

2020-10-20 05:48 UTC, inouetakuya commented
@pi0 @debs-obrien 

https://github.com/nuxt/nuxtjs.org/pull/755#issuecomment-712346353

I have gotten a invitation mail of this repository from @pi0, however I don't see have write access to merge this PR.

My view:

![image](https://user-images.githubusercontent.com/634357/96545373-39b56f00-12e3-11eb-8cb5-e0e7d6e2a45d.png)

2020-10-21 09:58 UTC, debs-obrien commented
@inouetakuya can you check now if you have permissions to merge. Thanks

2020-10-21 12:35 UTC, inouetakuya commented
@debs-obrien CC: @pi0 @aytdm 

It looks that I can merge this PR!! Thank you very much!! ☺️ 

![image](https://user-images.githubusercontent.com/634357/96720038-37d3d480-13e5-11eb-9bcb-433b829fdbfc.png)

2020-10-21 12:43 UTC, merged