directory-structure/layouts.md no
nuxt/nuxtjs.org pull request #980
Opened 2020-11-12 15:01 UTC by konu96

2020-11-14 15:10 UTC, inouetakuya requested changes
翻訳ありがとうございます！いくつかコメントしたので確認お願いします！

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +The error page is a *page component* which is always displayed when an error occurs (that is not thrown on the server-side).
原文が残っているようなので削除お願いします 🙏

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +エラーページはエラーが発生したときいつも表示される *ページコンポーネント*　です.(サーバーサイドで発生したものではない)
```suggestion
エラーページはエラーが発生したときいつも表示される *ページコンポーネント* です（サーバーサイドで発生したエラーではない）。
```

- 括弧は全角でお願いします（他の箇所も同様です）
- that はエラーのことなので明示してみました

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +このファイルは `layout` フォルダに置かれるが、ページとして扱われるべきです.
```suggestion
このファイルは `layout` フォルダに置かれますが、ページとして扱われるべきです。
```

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +上述したように、このレイアウトは特殊でテンプレートの中に `<Nuxt>` を含めるべきではありません。このレイアウトは、エラーが発生したときに表示されるコンポーネントとして表示されなければなりません (`404`, `500` など)。他のページコンポーネントと同様に、エラーページにも通常の方法でカスタムレイアウトを設定することができます。
```suggestion
上述したように、このレイアウトは特殊でテンプレートの中に `<Nuxt>` を含めるべきではありません。このレイアウトは、エラーが発生したときに表示されるコンポーネントとして表示されなければなりません（`404`, `500` など）。他のページコンポーネントと同様に、エラーページにも通常の方法でカスタムレイアウトを設定することができます。
```

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +  layout: 'blog' // you can set a custom layout for the error page
コード内のコメントは訳をお願いします

2020-11-14 15:10 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +デフォルトのエラーページのソースコードは [GitHub で手に入ります](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-error.vue).
```suggestion
デフォルトのエラーページのソースコードは [GitHub で参照できます](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-error.vue).
```

2020-11-16 13:24 UTC, konu96 commented
PTAL です 🙇‍♂️

2020-11-16 14:08 UTC, inouetakuya requested changes
もう 1点だけ、お願いします 🙏

2020-11-16 14:08 UTC, inouetakuya commented on content/ja/guides/directory-structure/layouts.md
> +`layout` ディレクトリの全てのファイル(_トップレベル_)は、ページコンポーネントの `layout` プロパティで使えるカスタムレイアウトが作られる。
```suggestion
`layout` ディレクトリの全てのファイル（_トップレベル_）は、ページコンポーネントの `layout` プロパティで使えるカスタムレイアウトが作られる。
```

括弧は全角でお願いします。

2020-11-16 14:42 UTC, konu96 commented
すみません. 漏れがありました 🙇

2020-11-16 14:57 UTC, aytdm reviewed
翻訳ありがとうございます。コメントしました

2020-11-16 14:57 UTC, aytdm commented on content/ja/guides/directory-structure/layouts.md
> +  // OR
こちらも翻訳をお願いします

```suggestion
  // または
```

2020-11-16 14:57 UTC, aytdm commented on content/ja/guides/directory-structure/layouts.md
> +description: レイアウトは Nuxt.js アプリのルック&フィールを変えるとき、とても役に立ちます。例えばサイドバーを含めたいときや、モバイルとデスクトップのための別々のレイアウトを持ちたいときなどに有用です。
アプリと略さずアプリケーションでお願いします。

```suggestion
description: レイアウトは Nuxt.js アプリケーションのルック&フィールを変えるとき、とても役に立ちます。例えばサイドバーを含めたいときや、モバイルとデスクトップのための別々のレイアウトを持ちたいときなどに有用です。
```

2020-11-16 14:57 UTC, aytdm commented on content/ja/guides/directory-structure/layouts.md
> +レイアウトは Nuxt.js アプリのルック&フィールを変えるとき、とても役に立ちます。例えばサイドバーを含めたいときや、モバイルとデスクトップのための別々のレイアウトを持ちたいときなどに有用です。
上記と同様です

2020-11-16 14:57 UTC, aytdm commented on content/ja/guides/directory-structure/layouts.md
> +`layout` ディレクトリの全てのファイル（_トップレベル_）は、ページコンポーネントの `layout` プロパティで使えるカスタムレイアウトが作られる。
文体は箇条書きなどを除き基本的にですます調でお願いします。
Ref: https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E6%96%87%E4%BD%93

2020-11-16 14:57 UTC, aytdm commented on content/ja/guides/directory-structure/layouts.md
> +上述したように、このレイアウトは特殊でテンプレートの中に `<Nuxt>` を含めるべきではありません。このレイアウトは、エラーが発生したときに表示されるコンポーネントとして表示されなければなりません（`404`, `500` など）。他のページコンポーネントと同様に、エラーページにも通常の方法でカスタムレイアウトを設定することができます。
こちらも全角でお願いします

```suggestion
上述したように、このレイアウトは特殊でテンプレートの中に `<Nuxt>` を含めるべきではありません。このレイアウトは、エラーが発生したときに表示されるコンポーネントとして表示されなければなりません（`404`、`500` など）。他のページコンポーネントと同様に、エラーページにも通常の方法でカスタムレイアウトを設定することができます。
```

2020-11-17 01:51 UTC, inouetakuya approved these changes
LGTM です！おつかれさまでした！

@aytdm OK であればマージお願いします〜

2020-11-17 12:59 UTC, aytdm approved these changes
ご対応ありがとうございます！
First time contribution 🎉🎉🎉

2020-11-17 12:59 UTC, merged