docs(ru): Translate directory features
nuxt/nuxtjs.org pull request #986
Opened 2020-11-14 22:32 UTC by zavvla

Added translate "features/deployment-targets" for RU

2020-11-14 22:33 UTC, zavvla commented
@DreaMinder make a review please

2020-11-15 17:54 UTC, DreaMinder requested changes
Hey @zavvla, nice work.
I noticed you added line breaks on every sentence comparing to the eng version. Is that intentional? Can we discuss that part?

2020-11-15 18:23 UTC, zavvla commented
Hi @DreaMinder.
Yes, this is intentional. In my opinion, it is easier to read text that does not have a codebase(pure code) this way. If something is wrong, please fix it.

2020-11-17 10:45 UTC, DreaMinder approved these changes

2020-11-17 10:45 UTC, DreaMinder commented on content/ru/guides/features/deployment-targets.md
> +Сгенерировав статическую версию Nuxt.js приложения, вы получаете все преимущества универсального приложения(SPA) работающего без сервера.
```suggestion
Сгенерировав статическую версию Nuxt.js приложения, вы получаете все преимущества универсального приложения (SPA) работающего без сервера.
```

2020-11-17 14:40 UTC, merged